### ISSUE TITLE
Namespaces

### ISSUE THREAD

**Issue by besinci** [MrDesjardins/WebForLocalizedUrl#1]
Hi, i have some issue;

//////
Multiple types were found that match the controller named 'Home'. This can happen if the route that services this request ('{controller}/{action}/{id}') does not specify namespaces to search for a controller that matches the request. If this is the case, register this route by calling an overload of the 'MapRoute' method that takes a 'namespaces' parameter.

The request for 'Home' has found the following matching controllers:
CleanSolution.Areas.Panel.Controllers.HomeController
CleanSolution.Controllers.HomeController
/////

I Added namespaces:

```
        routes.Add("LocalizedRoute", new TranslatedRoute(
                    "{controller}/{action}/{id}",
                    new RouteValueDictionary(new { controller = "Home", action = "Index", id = "" }),
                    translationTables,
                    new MvcRouteHandler()));


        routes.MapRoute(
            name: "Default",
            url: "{controller}/{action}/{id}",
            defaults: new { controller = "Home", action = "Index", id = UrlParameter.Optional },
            namespaces: new[] { "CleanSolution.Controllers" }
```

**Comment by MrDesjardins** [comment]
This is an issue that you would had with the default MVC routing too. That is why, in the article linked to this repository, I said that it needs to have Area defined to be full fledged ready. This example is for a solution without area. You have a problem because you have a HomeController in the Panel Area and one in the default one. I do not think that having the namespace defined is the right way to fix the issue. I believe that the Area should also work in the same way that I did in the code about Controller and Action which are localized.

**Comment by besinci** [comment]
I see, thank you for your response.
